sudo: required 
services: 
    - docker 

before_install:
    - docker build -t hemanth/react-test -f ./client/Dockerfile.dev ./client

      
script:
    - docker run hemanth/react-test npm test -- -- coverage 

after_success:

     - docker build -t hemanth/multi-client ./client 

     - docker build -t hemanth/multi-nginx ./nginx
     - docker build -t hemanth/multi-server ./server
     - docker build -t hemanth/multi-worker ./worker
     #Login to the docker cli
     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
     #Take those images and push them to docker hub
     - docker push hemanth/multi-client
     - docker push hemanth/multi-nginx
     - docker push hemanth/multi-server
     - docker push hemanth/multi-worker 

